### ISSUE TITLE
这个一键包和oneinstack有什么不同?未来会合并吗?

### ISSUE THREAD

**Issue by wedojava** [lj2007331/lnmp#92]
oneinstack我看还包含java环境的,不知道如果只是php服务器环境的话,oneinstack和lnmp这个节点的包有啥区别,作者更推荐用哪一个?在未来是否会合并?

另外,一直没明白LEMP和LNMP有啥区别,不都是NGINX吗?

这个问题搞明白了:https://lempstack.com

**Comment by Santino-Wu** [comment]
记得在作者的博客上有说过暂时的区别只在于是否支持Java开发环境。而LNMP和LEMP只是叫法不同，两者没有区别，引用来自[lemp.io](https://lemp.io/)首页的相关描述：

> Why LEMP instead of LNMP?
We go with LEMP due to the pronunciation for Nginx: Engine-X (en-juhn-ecks). Think of how in English, the article an is used instead of a for hour even though it begins with a consonant. The importance is the sound of the first letter rather than its written representation. Besides, LEMP is actually pronounceable and doesn’t sound like reciting the alphabet.

**Comment by wedojava** [comment]
谢谢,明白了

**Comment by lj2007331** [comment]
@wedojava @Santino-Wu 开发都是在oneinstack，lnmp只是注销了tomcat相关代码。
